//Defining our action type constants
export const AUTH_USER_REQUEST = 'AUTH_USER_REQUEST';
export const AUTH_USER_SUCCESS = 'AUTH_USER_SUCCESS';
export const AUTH_USER_FAILURE = 'AUTH_USER_FAILURE';
export const REGISTER_USER_REQUEST = 'REGISTER_USER_REQUEST';
export const REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS';
export const REGISTER_USER_FAILURE = 'REGISTER_USER_FAILURE';
export const FETCH_ORDERS_REQUEST = 'FETCH_ORDERS_REQUEST';
export const FETCH_ORDERS_SUCCESS = 'FETCH_ORDERS_SUCCESS';
export const FETCH_ORDERS_FAILURE = 'FETCH_ORDERS_FAILURE';
export const CHANGE_DRIVER_STATUS_REQUEST =
  'CHANGE_DRIVER_STATUS_REQUEST';
export const CHANGE_DRIVER_STATUS_SUCCESS =
  'CHANGE_DRIVER_STATUS_SUCCESS';
export const CHANGE_DRIVER_STATUS_FAILURE =
  'CHANGE_DRIVER_STATUS_FAILURE';
